name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: myPerfectWriting_qa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Show current working directory
        run: cd myPerfectWriting && pwd

      - name: Install dependencies
        run: cd myPerfectWriting_qa && npm install

      - name: Install Playwright Browsers
        run: cd myPerfectWriting && npx playwright install --with-deps

      - name: Run Playwright Tests
        run: cd myPerfectWriting && npx playwright test --reporter=html --output=test-reports

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: myPerfectWriting_qa/test-reports/
